#-------------------------------
# General Site Settings
baseURL = "https://asherawelan.github.io"
languageCode = "en-gb"
title = "Asher Awelan"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 9

#-------------------------------
# Main Menu
[menu]
#  [[menu.main]]
#    identifier = "home"
#    name = "Home"
#    url = "/"
#    weight = 1
#
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about"
#    weight = 2
#
#  [[menu.main]]
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact"
#    weight = 3

[params]
  logo = "/images/awelan-logo-black.png"
  description = "Asher Awelan"

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = "Asher Awelan"
    author__image = "/images/asher-awelan.jpg"
    author__avatar = "/images/asher-awelan.jpg"
    author__description = "I'm Asher, I lead teams. I use this space to reflect on agile practice, software development, event production and other adventures."

  [[params.social]]
    icon = "ion-logo-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "ion-logo-linkedin"
    name = "LinkedIn"
    link = "https://facebook.com"

  # Other icons can be found at https://ionicons.com/v4/

  #-------------------------------
  # Newsletter (partials/footer-widgets/widget-subscribe.html)
  [params.mailchimp]
    mailchimp__title = "Get Interesting News"
    mailchimp__text = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
    mailchimp__identifier = "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
    mailchimp__button__text = "Subscribe" # Add your button text

  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your email for contant form

    # NOTE
    # Hally comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    disqusShortname = ""


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false